### PR TITLE
 Gun Ending Change

### PR DESCRIPTION
**Pull request by tTDeimos**
guns when they are out of ammo will disappear by burning instead of falling out of your hand being unpickable and die in a few seconds

### CODE REVIEW

**Comment by tTDeimos** [comment]
I can make it into a explosion that doesnt hurt the owner but zombies

**Comment by Kuift** [comment]
Best way to go about it would be to make it so that the gun dismantle itself into multiple part "explosively".
Right now, the way it is done is underwhelming.

**Comment by tTDeimos** [comment]
You want the gun parts to diseappear after a few seconds? and also do you want explosion to damage anything

**Comment by ferrezinhre** [comment]
Adding something for sake of adding is pointless, gibs and explosion, why? What is point of that?

**Comment by tTDeimos** [comment]
improving?

**Comment by ferrezinhre** [comment]
> improving?

This is not improving, rather an outright downgrade for sake of pointless change.

**Comment by tTDeimos** [comment]
no idea how thats being a downgrade but okay

**Comment by tTDeimos** [comment]
I will leave it to kuift

**Comment by Kuift** [comment]
I really like the way it is in main and as it stand, when testing, this felt like a downgrade. Thanks for trying something out though

**Pull request closed without merging**
